### ISSUE TITLE
Issues accesing Teams with Deletated scenario

### ISSUE THREAD

**Issue by gabrielantohi** [microsoft/edu-assignments-graph-sdk#15]
Hi there,

I have configured my ogle migration app with the Delegated scenario. In the app registration I have entered the https://localhost, as er documentation.
When I try to sign in into Teams, to get the M365 Edu credentials, I receive an error:

_AADSTS50011: The redirect URI 'http://localhost:53299' specified in the request does not match the redirect URIs configured for the application '80dd4d77-a15d-4437-bc42-83127fc454b3'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this._

 
![image](https://github.com/microsoft/edu-assignments-graph-sdk/assets/63408874/d9cd2580-985c-4b7c-9ff7-be23c0b0f9a1)

**Comment by gabrielantohi** [comment]
... if I remove the localhost from RedirectURi I got: _AADSTS500113: No reply address is registered for the application._

**Comment by cristobal-buenrostro** [comment]
Hey @gabrielantohi, the redirect url must the match including the port number.
Feel free to reach out the assignments team directly for any further issue regarding google importer tool
